### ISSUE TITLE
Issue with the newest CS-Corelib in 1.16.3

### ISSUE THREAD

**Issue by CSONGOS** [TheBusyBiscuit/sensibletoolbox#6]
Hi! I found an issue with the plugin that I have a 1.16.3 server and I downloaded Slimefun4's and CS-CoreLib's newest dev version but when I downloaded the latest version of SensibleToolbox it says that CS-CoreLib Updater cant found the sensibletoolbox on Bukkit dev, and cant enable it. [SensibleToolbox - Updater] Could not connect to BukkitDev, is it down? and this is the same issue with SlimeMobs and SlimefunOres plugin in 1.16.3 Can you help me to fix this and use these 3 plugins in 1.16.3 with the Slimefun4 and without any issue?

**Comment by TheBusyBiscuit** [comment]
The "latest" version of SensibleToolbox is for Minecraft 1.9, not 1.16...

**Comment by TheBusyBiscuit** [comment]
No, it literally says "(1.9.X Only)" on the BukkitDev page, it's been 4 years since the last release.

**Comment by CSONGOS** [comment]
Where i got from the plugin it only said that 1.9 and i thought that a plugin that can be used in 1.9 can be used in 1.16, but now I see it is imposible

**Comment by CSONGOS** [comment]
But is there any way for me to update it to 1.16.3 or not? Because if it could be possible i will try it.

**Comment by TheBusyBiscuit** [comment]
It's open-source, you're on the GitHub repository of STB right now, feel free to try and submit a pull request if you want.

**Comment by CSONGOS** [comment]
I am beginner right now in this coding so can you give me some introductions or hint to what i have to edit to make it working in 1.16.3 and work right with its dependences like, Slimefun4, CS-CoreLib and ProtocolLib?

**Comment by TheBusyBiscuit** [comment]
> what i have to edit to make it working in 1.16.3 and work right with its dependences like, Slimefun4, CS-CoreLib and ProtocolLib?

Quite literally, everything.
This isn't a very straight-forward task if you have little experience with this.

**Comment by CSONGOS** [comment]
So it will take weeks or months :)

**Comment by TheBusyBiscuit** [comment]
At best.

If you really wanna try getting your hands on this, I suggest joining the Slimefun4 discord server: https://discord.gg/fsD4Bkh
It isn't really about STB - I could create a seperate channel for it though - but there are a lot of experienced developers who can provide you guidance or even help update STB itself. I myself have already done half of the work throughout the last 9 months, starting back in January. But it is nowhere near done, I think that gives a pretty good grasp on what scale we are talking about here.

So feel free to join the discord, I am sure some others would love to see this being revived too. I would recommend to start by forking the repository, importing it into your IDE of choice and then just see where the compilation errors and warnings take you XD
